project:
  type: website
  output-dir: docs

website:
  title: "Jason Coupet, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd
      - Courses.qmd
      - Blog.qmd
      - Illicit Market Study.qmd

format:
  html:
    theme:
      - pulse
      - pulse
      - pulse
    css: styles.css
    toc: true



